export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';

export const ADD_FAVORITES = 'ADD_FAVORITES';
export const REMOVE_FAVORITES = 'REMOVE_FAVORITES';
export const REMOVE_ALL_FAVORITES = 'REMOVE_ALL_FAVORITES';
export const GET_LOCALSTORAGE_FAVS = 'GET_LOCALSTORAGE_FAVS';
export const FETCH_FAVORITE = 'FETCH_FAVORITE';
export const FETCH_FAVORITE_START = 'FETCH_FAVORITE_START';
export const FETCH_FAVORITE_SUCCESS = 'FETCH_FAVORITE_SUCCESS';
export const FETCH_FAVORITE_FAIL = 'FETCH_FAVORITE_FAIL';

export const ERROR_CLOSE = 'ERROR_CLOSE';

export const MODE_SELECTOR = 'MODE_SELECTOR';